# Generated by Django 5.0 on 2025-12-10 01:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Icono FontAwesome', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('capacity', models.PositiveIntegerField(help_text='Capacidad máxima del lugar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('facilities', models.TextField(blank=True, help_text='Parking, WiFi, etc.', verbose_name='Facilidades')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'venues',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='venues_city_c32704_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Resumen breve para listados', max_length=500, verbose_name='Descripción corta')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('registration_start', models.DateTimeField(verbose_name='Inicio de registro')),
                ('registration_end', models.DateTimeField(verbose_name='Fin de registro')),
                ('is_free', models.BooleanField(default=False, verbose_name='Evento gratuito')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para sin límite', null=True, verbose_name='Máximo de asistentes')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/', verbose_name='Imagen banner')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/%Y/%m/', verbose_name='Imagen miniatura')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('ongoing', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas', max_length=500, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category', verbose_name='Categoría')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'events',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['-start_date', 'status'], name='events_start_d_8ace4b_idx'), models.Index(fields=['category', 'is_published'], name='events_categor_6496af_idx')],
            },
        ),
    ]
