# Generated by Django 5.0 on 2025-12-10 01:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('dietary_restrictions', models.TextField(blank=True, verbose_name='Restricciones alimentarias')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Requerimientos especiales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('checked_in', 'Ingresado'), ('cancelled', 'Cancelado'), ('no_show', 'No asistió')], default='pending', max_length=20, verbose_name='Estado')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('receive_reminders', models.BooleanField(default=True, verbose_name='Recibir recordatorios')),
                ('receive_updates', models.BooleanField(default=True, verbose_name='Recibir actualizaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_attendees', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'db_table': 'attendees',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('location', models.CharField(blank=True, help_text='Ej: Puerta A, Registro Principal', max_length=200, verbose_name='Ubicación')),
                ('device_info', models.CharField(blank=True, max_length=300, verbose_name='Información del dispositivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='attendees.attendee', verbose_name='Asistente')),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Check-in',
                'verbose_name_plural': 'Registros de Check-in',
                'db_table': 'checkin_logs',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anónima')),
                ('allow_multiple_responses', models.BooleanField(default=False, verbose_name='Permitir múltiples respuestas')),
                ('available_from', models.DateTimeField(verbose_name='Disponible desde')),
                ('available_until', models.DateTimeField(verbose_name='Disponible hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('text', 'Texto libre'), ('rating', 'Calificación (1-5)'), ('multiple_choice', 'Opción múltiple'), ('checkbox', 'Casillas de verificación'), ('yes_no', 'Sí/No')], max_length=20, verbose_name='Tipo de pregunta')),
                ('options', models.JSONField(blank=True, help_text='Para preguntas de opción múltiple o checkboxes', null=True, verbose_name='Opciones')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attendees.survey', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'db_table': 'survey_questions',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='attendees.attendee', verbose_name='Asistente')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attendees.surveyquestion', verbose_name='Pregunta')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attendees.survey', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'db_table': 'survey_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['event', 'status'], name='attendees_event_i_219a28_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['email'], name='attendees_email_3b8b72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user', 'event')},
        ),
    ]
