# Generated by Django 5.0 on 2025-12-10 01:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del ticket')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('quantity_available', models.PositiveIntegerField(help_text='Total de tickets de este tipo', verbose_name='Cantidad disponible')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Cantidad vendida')),
                ('max_per_order', models.PositiveIntegerField(default=10, help_text='Máximo de tickets que se pueden comprar en una sola orden', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo por orden')),
                ('sale_start', models.DateTimeField(verbose_name='Inicio de ventas')),
                ('sale_end', models.DateTimeField(verbose_name='Fin de ventas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('includes_food', models.BooleanField(default=False, verbose_name='Incluye comida')),
                ('includes_drink', models.BooleanField(default=False, verbose_name='Incluye bebida')),
                ('includes_parking', models.BooleanField(default=False, verbose_name='Incluye parking')),
                ('includes_merchandise', models.BooleanField(default=False, verbose_name='Incluye merchandising')),
                ('benefits_description', models.TextField(blank=True, verbose_name='Descripción de beneficios')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Tickets',
                'db_table': 'ticket_types',
                'ordering': ['event', 'display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de ticket')),
                ('qr_code', models.CharField(blank=True, max_length=255, verbose_name='Código QR')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID de transacción')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio original')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final')),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('used', 'Usado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='reserved', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Razón de cancelación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='attendees.attendee', verbose_name='Asistente')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype', verbose_name='Tipo de ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del descuento')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usos máximos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces usado')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Usos máximos por usuario')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra mínima requerida')),
                ('valid_from', models.DateTimeField(verbose_name='Válido desde')),
                ('valid_until', models.DateTimeField(verbose_name='Válido hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.event', verbose_name='Evento específico')),
                ('applicable_ticket_types', models.ManyToManyField(blank=True, related_name='discount_codes', to='tickets.tickettype', verbose_name='Tipos de ticket aplicables')),
            ],
            options={
                'verbose_name': 'Código de Descuento',
                'verbose_name_plural': 'Códigos de Descuento',
                'db_table': 'discount_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active'], name='ticket_type_event_i_c71083_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_code'], name='tickets_ticket__2ef6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['buyer', 'status'], name='tickets_buyer_i_7f0e85_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'status'], name='tickets_ticket__46ee73_idx'),
        ),
    ]
