# Generated by Django 5.0 on 2025-12-10 01:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('min_contribution', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Contribución mínima')),
                ('max_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Contribución máxima')),
                ('benefits', models.TextField(help_text='Lista de beneficios separados por saltos de línea', verbose_name='Beneficios incluidos')),
                ('priority_level', models.PositiveIntegerField(default=0, help_text='Mayor número = mayor prioridad', verbose_name='Nivel de prioridad')),
                ('logo_size', models.CharField(default='medium', help_text='small, medium, large, xlarge', max_length=50, verbose_name='Tamaño del logo')),
                ('homepage_featured', models.BooleanField(default=False, verbose_name='Destacado en página principal')),
                ('speaking_opportunity', models.BooleanField(default=False, verbose_name='Oportunidad de hablar')),
                ('booth_space', models.BooleanField(default=False, verbose_name='Espacio para stand')),
                ('complimentary_tickets', models.PositiveIntegerField(default=0, verbose_name='Tickets de cortesía')),
                ('vip_tickets', models.PositiveIntegerField(default=0, verbose_name='Tickets VIP')),
                ('color', models.CharField(default='#CCCCCC', help_text='Código hexadecimal, ej: #FFD700', max_length=7, verbose_name='Color representativo')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel de Patrocinio',
                'verbose_name_plural': 'Niveles de Patrocinio',
                'db_table': 'sponsor_tiers',
                'ordering': ['-priority_level', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Persona de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Sitio web')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Logo')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sponsors/banners/', verbose_name='Banner')),
                ('status', models.CharField(choices=[('prospective', 'Prospecto'), ('negotiating', 'En negociación'), ('confirmed', 'Confirmado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='prospective', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sponsors', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de cuenta')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de contribución')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('completed', 'Completado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado de pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('contract_signed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de firma de contrato')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago')),
                ('custom_benefits', models.TextField(blank=True, help_text='Beneficios adicionales o personalizados', verbose_name='Beneficios personalizados')),
                ('booth_number', models.CharField(blank=True, max_length=20, verbose_name='Número de stand')),
                ('speaking_slot', models.DateTimeField(blank=True, null=True, verbose_name='Horario para presentación')),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='sponsors/contracts/%Y/%m/', verbose_name='Documento de contrato')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible públicamente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='events.event', verbose_name='Evento')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sponsors.sponsor', verbose_name='Patrocinador')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to='sponsors.sponsortier', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Patrocinio',
                'verbose_name_plural': 'Patrocinios',
                'db_table': 'sponsorships',
                'ordering': ['-contribution_amount'],
            },
        ),
        migrations.CreateModel(
            name='SponsorBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=200, verbose_name='Nombre del beneficio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='sponsors/benefits/%Y/%m/', verbose_name='Documento de evidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_benefits', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_benefits', to='sponsors.sponsorship', verbose_name='Patrocinio')),
            ],
            options={
                'verbose_name': 'Beneficio de Patrocinador',
                'verbose_name_plural': 'Beneficios de Patrocinadores',
                'db_table': 'sponsor_benefits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='events',
            field=models.ManyToManyField(related_name='sponsors', through='sponsors.Sponsorship', to='events.event', verbose_name='Eventos'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.sponsortier', verbose_name='Nivel de patrocinio'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['event', 'is_public'], name='sponsorship_event_i_f0737c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorship',
            unique_together={('sponsor', 'event')},
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['status', 'is_active'], name='sponsors_status_b1c956_idx'),
        ),
    ]
